apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: fluxcd/source-controller
  newName: registry.nordix.org/allies/source-controller
  newTag: v1.7.4-est-2
